services:
  workload-tool:
    build: .
    image: workload-tool:v0.4.21-3
    container_name: workload-tool
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - WORKLOAD_DATA_DIR=/app/data
